- 학번: 2021136128
- 이름: 조은샘

# a_tensor_initialization.py

In [6]:
import torch #PyTorch 모듈 가져오기

- PyTorch: 딥러닝을 위한 Python 라이브러리

#### * 클래스와 메소드 이용하여 텐서 생성하는 방법
#### * GPU 사용법

In [9]:
# torch.Tensor class
# 클래스 이용 텐서 생성
t1 = torch.Tensor([1, 2, 3], device='cpu') #텐서 저장 위치 CPU로 지정

# 텐서 정보 출력
print(t1.dtype)   # 텐서 데이터 타입 >>> torch.float32
print(t1.device)  # 텐서 저장된 장치 >>> cpu
print(t1.requires_grad)  # 텐서의 기울기 요구 여부 >>> False
print(t1.size())  # 텐서 크기 >>> torch.Size([3])
print(t1.shape)   # 텐서 모양 출력 >>> torch.Size([3])

# 텐서 GPU, CPU로 이동시키는 법
# if you have gpu device
## t1_cuda = t1.to(torch.device('cuda')) # GPU로 텐서 이동
# or you can use shorthand
## t1_cuda = t1.cuda() # 축약형
t1_cpu = t1.cpu() # CPU로 텐서 이동

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [10]:
# torch.tensor function
# 메소드 이용 텐서 생성
t2 = torch.tensor([1, 2, 3], device='cpu') #텐서 저장 위치 CPU로 지정

# 텐서 정보 출력 - 위와 텐서 데이터 타입만 다름
print(t2.dtype)   # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # >>> torch.Size([3])
print(t2.shape)   # >>> torch.Size([3])

# 텐서 GPU, CPU로 이동시키는 법 - 위와 동일
# if you have gpu device
## t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
## t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


#### * 텐서 생성에 따른 텐서 모양과 차원 확인

In [12]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)
# 0개의 원소를 갖는 0차원 텐서

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim) 
# 1개의 원소를 갖는 1차원 텐서
# 1개씩 1개

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)
# 5개의 원소를 갖는 1차원 텐서
# 5개씩 1개

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)                      
# 5개의 원소를 갖는 2차원 텐서
# 1개씩 2개

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)
# 6개의 원소를 갖는 2차원 텐서
# 2개씩 3개

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)
# 6개의 원소를 갖는 3차원 텐서
# (1개씩 2개)가 3개

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)
# 6개의 원소를 갖는 4차원 텐서
# ((1개씩 2개)가 1개)가 3개

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)
# 18개의 원소를 갖는 4차원 텐서
# ((3개씩 2개)가 1개)가 3개

a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)
# 18개의 원소를 갖는 5차원 텐서
# (((1개씩 3개)가 2개)가 1개)가 3개

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)
# 20개의 원소를 갖는 2차원 텐서
# 5개씩 4개

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)
# 20개의 원소를 갖는 3차원 텐서
# (5개씩 1개)가 4개

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
# 모양(비표준 표현) -> shape: torch.Size([4, 1, 2, 3 or 2])
# 오류 발생: 텐서의 4 번째 축의 크기가 모두 동일하지 않음

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3
torch.Size([4, 1, 2, 2]) 4


- 텐서의 모든 축의 크기는 동일하다는 특징이 있다.

# b_tensor_initialization_copy

In [19]:
import torch
import numpy as np #  NumPy 라이브러리를 np 별명으로 가져오기

- Numpy 라이브러리: 수치 계산을 위한 라이브러리로, 다차원 배열을 지원한다.

#### * 리스트를 텐서로 변환

In [24]:
l1 = [1, 2, 3]
print(type(l1[0])) # + 리스트의 원소의 타입 >>> <class 'int'>
t1 = torch.Tensor(l1) 
print(t1.dtype) # + 데이터 타입: 클래스에 의해 결정 >>> torch.float32

l2 = [1, 2, 3]
t2 = torch.tensor(l2) 
print(t2.dtype) # + 데이터 타입: 인자 타입에 의해 결정 >>> torch.int64

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) 
print(t3.dtype) # + 데이터 타입: 인자 타입에 의해 결정 >>> torch.int64

# 리스트 원소 변경
l1[0] = 100
l2[0] = 100
l3[0] = 100

# 텐서 출력
print(t1)
print(t2)
print(t3)

# 모든 텐서의 데이터 값이 변경되지 않음
# 모든 변환 방법에서 리스트와 변환된 텐서는 깊은 복사 됨 (공유 안함)

<class 'int'>
torch.float32
torch.int64
torch.int64
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


#### * numpy 배열을 텐서로 변환

In [27]:
l4 = np.array([1, 2, 3])
print(l4.dtype) # + numpy 배열의 타입 >>> int32
t4 = torch.Tensor(l4) 
print(t4.dtype) # + 데이터 타입: 클래스에 의해 결정 >>> torch.float32

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)
print(t5.dtype) # + 데이터 타입: 클래스에 의해 결정 >>> torch.int32

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)
print(t6.dtype) # + 데이터 타입: 클래스에 의해 결정 >>> torch.int32

# numpy 배열 원소 변경
l4[0] = 100
l5[0] = 100
l6[0] = 100

# 텐서 출력
print(t4)
print(t5)
print(t6)

# torch.as_tensor()로 numpy 배열을 텐서로 변환한 경우
    # 이 경우만 텐서의 데이터가 동일하게 변경되었음
    # 이 변환 방법에서 numpy 배열과 변환된 텐서는 얕은 복사 됨 (공유 함)
# torch.Tensor()와 torch.tensor()로 변환한 경우
    # 텐서의 데이터가 변경되지 않았음
    # 이 두 변환 방법에서 numpy 배열과 변환된 텐서는 깊은 복사 됨 (공유 안함)

int32
torch.float32
torch.int32
torch.int32
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


# c_tensor_initialization_constant_values.py

In [28]:
import torch

#### * 특정 값을 갖는 텐서 생성

In [35]:
# 지정된 크기로 텐서를 생성하고, 

# 모든 원소가 1인 지정된 크기의 텐서 생성 
t1 = torch.ones(size=(5,))  # or torch.ones(5)
                            # 모든 원소 1이고,
                            # 원소가 5개이고, 1차원인 텐서 생성
t1_like = torch.ones_like(input=t1) # 입력 텐서와 같은 크기, 데이터 타입의 1로 채워진 텐서 생성
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1.dtype) # + 데이터 타입 >>> torch.float32

# 모든 원소가 0인 지정된 크기의 텐서 생성 
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
                             # 모든 원소 0이고,
                             # 원소가 6개이고, 1차원인 텐서 생성
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2.dtype) # + 데이터 타입 >>> torch.float32

# 초기화되지 않은 지정된 크기의 텐서 생성 (쓰레기 값 갖음)
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
                             # 모든 원소가 초기화 되지 않고,
                             # 원소가 4개이고, 1차원인 텐서 생성
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])
print(t3.dtype) # + 데이터 타입 >>> torch.float32

# 지정된 크기의 항등 행렬 생성
t4 = torch.eye(n=3) # 크가 3x3인 항등 행렬 생성
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
torch.float32
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
torch.float32
tensor([ 1.0000e+00,         nan, -3.1441e-35,  4.0778e-43])
tensor([0.0000e+00, 6.9795e-39, 1.4013e-45, 0.0000e+00])
torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values.py

In [36]:
import torch

#### * 램덤 텐서 생성

In [43]:
# 데이터 값: 10 이상 20 미만의 랜덤 정수로 구성된 1x2 크기의 텐서 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

# 0 이상 1 미만의 랜덤 값으로 구성된 1x3 크기의 텐서 생성
t2 = torch.rand(size=(1, 3))
print(t2)

# 평균 0, 표준 편차 1을 따르는 정규 분포에서 랜덤 값으로 구성된 1x3 크기의 텐서 생성
t3 = torch.randn(size=(1, 3))
print(t3)

# 평균 10.0, 표준 편차 1.0인 정규 분포에서 랜덤 값으로 구성된 3x2 크기의 텐서 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[17, 12]])
tensor([[0.0453, 0.5035, 0.9978]])
tensor([[0.7419, 0.5923, 0.2908]])
tensor([[ 9.2270, 10.0961],
        [ 9.4067,  9.5878],
        [10.0763, 11.1161]])


#### * 범위를 지정한 텐서 생성

In [45]:
# 시작 값 0.0부터 종료 값 5.0까지를 균일하게 나눈 3개의 값으로 구성된 텐서 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# 0부터 4까지의 값을 가지는 1차원 텐서를 생성
t6 = torch.arange(5)
print(t6)

tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


#### * 시드와 랜덤 텐서 관계

In [48]:
torch.manual_seed(1729) # 난수 생성 시드 설정
random1 = torch.rand(2, 3) # 랜덤 텐서 생성
print(random1)

random2 = torch.rand(2, 3) # 랜덤 텐서 생성
print(random2)

print()

torch.manual_seed(1729)  # 같은 값으로 시드 설정
random3 = torch.rand(2, 3) #랜덤 텐서 생성
print(random3)

random4 = torch.rand(2, 3) #랜덤 텐서 생성
print(random4)

# 시드 설정 후 랜덤 텐서를 생성할 때마다 랜덤 값이 변함
# 한 시드에 대한 변하는 랜덤 값은 매번 동일함

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion.py

In [49]:
import torch

#### * 텐서 타입 변환 1

In [50]:
# 기본 타입으로 생성 (torch.float32)
a = torch.ones((2, 3)) # 모든 원소가 1인 2x3 크기의 텐서 생성
print(a.dtype) # >>> torch.float32

# 타입 지정으로 생성 (torch.int16)
b = torch.ones((2, 3), dtype=torch.int16)  # 모든 원소가 1이고, 데이터 타입을 int16으로 지정한 2x3 크기의 텐서 생성
print(b)

# 타입 지정으로 생성 (torch.float64)
c = torch.rand((2, 3), dtype=torch.float64) * 20. # 랜덤 값의 기본 범위는 0이상 1미만
                                                  # 텐서의 모든 데이터에 20을 곱해지므로 랜덤 값의 범위는 0이상 20미만이 됨
print(c)

# 텐서의 데이터 타입을 int16에서 int32로 변환
d = b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


#### * 텐서 타입 변환 2: double, short

In [56]:
# 텐서 생성 시에 매개변수 활용하여 타입 지정
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

# double(), short() 메소드를 사용하여 타입 변환
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()


# to() 메소드를 사용하여 타입 변환
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

# type() 메소드를 사용하여 타입 변환
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

# 위 4가지 경우 모두 같은 타입으로 변환 됨
print(double_d.dtype) # >>> torch.float64
print(short_e.dtype) # >>> torch.int16

# 두 텐서의 곱셈 연산 결과
double_f = torch.rand(5, dtype=torch.double) # torch.float64 타입인 랜덤 텐서 생성
short_g = double_f.to(torch.short) # 텐서의 타입을 torch.int16로 변환한 텐서 생성
print((double_f * short_g).dtype) # >>> torch.float64


torch.float64
torch.int16
torch.float64


- PyTorch에서 다른 데이터 타입의 텐서를 곱셈하면, 결과의 데이터 타입은 연산에 참여한 텐서 중 더 "높은" 데이터 타입으로 자동 변환된다. 
- "높은" 데이터 타입: 더 큰 범위의 숫자를 나타낼 수 있는 데이터 타입을 의미한다.

# f_tensor_operations.py

In [62]:
import torch

# 크기가 같은 두개의 텐서 생성
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))

#### * 텐서 연산: 덧셈

In [58]:
# 두 텐서 덧셈 연산하여 저장
t3 = torch.add(t1, t2) # 메소드 이용
t4 = t1 + t2 # 연산자 이용

# 결과 출력
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


#### * 텐세 연산: 뺄셈

In [59]:
# 두 텐서 뺄셈 연산하여 저장
t5 = torch.sub(t1, t2) # 메소드 이용
t6 = t1 - t2 # 연산자 이용

# 결과 출력
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### * 텐세 연산: 곱셈

In [60]:
# 두 텐서 곱셈 연산하여 저장
t7 = torch.mul(t1, t2) # 메소드 이용
t8 = t1 * t2 # 연산자 이용

# 결과 출력
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### * 텐세 연산: 나눗셈

In [61]:
# 두 텐서 나눗셈 연산하여 저장
t9 = torch.div(t1, t2) # 메소드 이용
t10 = t1 / t2 # 연산자 이용

# 결과 출력
print(t9)
print(t10)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


- 메소드, 연산자를 이용하는 연산하는 두 방법 모두 같은 결과가 나왔다.
- 텐서의 데이터가 각각 매칭되어 연산 되었다.

# g_tensor_operations_mm.py

#### * 텐서 내적, 텐서의 곱셈

In [11]:
# torch.dot()을 사용하여 1차원 텐서의 내적을 계산하여 저장
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size()) # >>> tensor(7) torch.Size([])
                     # 계산 결과: 0차원인 스칼라

# torch.mm()을 사용하여 2차원 텐서의 곱셈을 계산히여 저장
t2 = torch.randn(2, 3) # 2x3
t3 = torch.randn(3, 2) # 3x2
t4 = torch.mm(t2, t3)
print(t4, t4.size()) # >>> tensor([[1.6750, 2.2840], [0.0956, 1.0294]]) torch.Size([2, 2])

# torch.bmm()을 사용하여 3차원 텐서의 곱셈을 계산히여 저장
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size()) # >>> torch.Size([10, 3, 5])


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


- torch.dot()
  : 두 1차원 텐서 간의 내적 계산. 스칼라값 반환.
  : 두 텐서 원소 개수 일치해야함.
- torch.mm()
  : 두 2차원 텐서 간의 텐서의 곱셈만 계산.
  : (n x m) by (m x p) -> (n x p)
  : broadcasting을 지원 안함.
- torch.bmm()
  : 두 3차원 텐서 간의 텐서의 곱셈 계산.
  : (b x n x m) by (b x m x p) -> (b x n x p)
  : broadcasting을 지원 안함.

# h_tensor_operations_matmul.py

In [63]:
import torch

#### * 다차원 텐서 곱

In [ ]:
텐서 곱 (브로드캐스팅: 크기가 서로 다른 텐서를 자동으로 맞춰주는 기능)
mm은 브로드캐스팅이 불가능하다는 차이점이 있음
규칙 주의

In [12]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])
# 1차원 x 1차원 -> 스칼라 (0차원)

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])
# 2차원 x 1차원 -> 1차원

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])
# 3차원 x 1차원 -> 2차원

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])
# 3차원 x 3차원 -> 3차원

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])
# 3차원 x 2차원 -> 3차원

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


- 브로드캐스팅 기능 제공하므로 크가가 맞지 않는 연산에 대해 자동으로 크기를 맞춰서 연산을 수행한다.

# i_tensor_broadcasting.py

In [65]:
import torch

#### * 연산자와 메소드를 통한 브로드캐스팅 연산

In [66]:
# 1차원과 스칼라의 곱셈 연산 
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) # 결과: 1차원
               # 모든 원소에 스칼라 값 곱해짐

tensor([2., 4., 6.])


In [67]:
# 2차원과 1차원의 뺄셈 연산 (브로드캐스팅)
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # 결과: 2차원
               # 1차원 텐서가 2차원 텐서에 맞춰져 뺄셈 이루어짐

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [68]:
# 2차원과 스칼라의 사칙연산 (브로드캐스팅)
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0) 
print(t5 / 2.0)  # t5.div(2.0)
# 결과: 모두 2차원
# 스칼라가 2차원 텐서에 맞춰져 사칙연산 이루어짐

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [69]:
# 함수를 이용하여 나눗셈 연산 (브로드캐스팅)
def normalize(x): # 인자에 대하여 스칼라와 나눗셈 연산 값 반환
  return x / 255

t6 = torch.randn(3, 28, 28) # 3차원 텐서
print(normalize(t6).size()) # 스칼라가 3차원에 맞춰져서 나눗셈 계산 후 반환 받음

torch.Size([3, 28, 28])


#### * 다양한 차원 조합에 따른 브로드캐스팅 덧셈 연산

In [74]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]]) # t8이 t7에 맞춰 연산
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]]) # t9이 t7에 맞춰 연산
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]]) # t8과 t9이 서로 맞춰 연산
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]]) # t10이 t7 맞춰 연산

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


#### * ones, rand, empty 메소드로 텐서 생성하여 브로드캐스팅 연산

In [71]:
# 일치하지 않는 축에 대해 값이 큰 쪽으로 맞춰서 연산

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape) # >>> torch.Size([4, 3, 2])

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape) # >>> torch.Size([4, 3, 2])

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape) # >>> torch.Size([4, 3, 2])

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size()) # >>> torch.Size([5, 3, 4, 1])

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [72]:
# 일치하지 않는 축에 대해 값이 큰 쪽으로 맞춰서 연산

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])


# 브로드캐스트 불가로 인한 오류
# 3번째 축의 크기가 각각 2, 3으로 
# 둘 중 하나가 1이거나 존재하지 않아야 한다는 규칙 만족 못함

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


 <브로드캐스트 규칙>
- 각 텐서는 최소한 한 차원은 가지고 있다.
- 뒤 쪽에서 시작하여 차원의 크기는 동일해야하고, 다르다면 그 중 하나는 1이거나 존재하지 않아야 한다.

#### * 스칼라 연산과 제곱 연산에 대한 브로드캐스팅

In [73]:
# 1차원 텐서와 스칼라의 곱셈 연산 (브로드캐스팅)
t27 = torch.ones(4) * 5
print(t27)  # 1차원 결과 >>> tensor([ 5, 5, 5, 5])

# 1차원 텐서와 스칼라의 제곱 연산 (브로드캐스팅)
t28 = torch.pow(t27, 2)
print(t28)  # 1차원 결과 >>> tensor([ 25, 25, 25, 25])

# 1차원 텐서와 1차원 텐서의 제곱 연산 (브로드캐스팅)
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # 1차원 텐서 >>> tensor([   1.,    4.,   27.,  256.])


tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


- 텐서의 차원과 크기가 달라도 브로드캐스팅을 통하여 차원을 맞춘 후에 연산을 수행한다.

# j_tensor_indexing_slicing.py

In [76]:
import torch

#### * 텐서의 인덱싱, 슬라이싱

In [82]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# 인덱싱: 첫 번째 행 선택
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])

# 슬라이싱 및 인덱싱: 모든 행에서 두 번째 열 선택
print(x[:, 1])  # >>> tensor([1, 6, 11])

# 인덱싱: 두 번째 행의 세 번째 열 선택
print(x[1, 2])  # >>> tensor(7)

#슬라이싱 및 인덱싱: 모든 행에서 마지막 열 선택
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


#### * 다차원 슬라이싱

In [83]:
# 슬라이싱: 두 번째 행부터 끝까지 선택
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])

# 슬라이싱: 두 번째 행부터 끝까지, 네 번째 열부터 끝까지 선택
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


#### * 인덱싱과 슬레이싱을 이용한 값 변경

In [84]:
# 두 번째부터 네 번째 행의 세 번째 열에 1 할당
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

# 두 번째부터 네 번째 행과 두 번째부터 네 번째 열 선택하여 출력
print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [85]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

# 첫 두 행 선택
print(z[:2])

# 두 번째부터 끝까지 행과 두 번째부터 세 번째 열 선택
print(z[1:, 1:3])

# 모든 행과 두 번째부터 끝까지 열 선택
print(z[:, 1:])

# 두 번째부터 끝까지 행과 두 번째부터 세 번째 열의 값에 0 할당
z[1:, 1:3] = 0
print(z)


tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.py

In [86]:
import torch

#### * 텐서 재구성: 텐서 모양 변경

In [94]:
# (2,3) 텐서 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# view 메소드로 (3,2) 텐서로 변경
t2 = t1.view(3, 2)  # Shape becomes (3, 2)

# reshape 메소드로 (1,6) 텐서로 변경
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)

# 출력: 텐서 모양이 변경되었음
print(t2) # (3,2)
print(t3) # (1, 6)

# view의 텐서 모양 변경을 이용하여 텐서 생성
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


#### * 차원 추가 및 삭제

In [95]:
# 차원 삭제 (squeeze 메소드)

# Original tensor with shape (1, 3, 1)
# 3차원 텐서 생성
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
# 크기가 1인 모든 차원 삭제
t7 = t6.squeeze()  # Shape becomes (3,) 

# Remove dimension at position 0
# 특정 위치의 차원 삭제
t8 = t6.squeeze(0)  # Shape becomes (3, 1) 

# 차원이 삭제된 텐서 출력
print(t7) #1, 3차원 제거 됨
print(t8) # 3차원 제거 됨

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [96]:
# 차원 추가 (unsqueeze 메소드) 

# Original tensor with shape (3,)
# 1차원 텐서 생성 
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
# 지정된 위치에 차원 크기가 1인 차원 추가
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10) # 1차원에 추가 됨

# 2차원 텐서 생성
t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)

# 지정된 위치에 차원 크기가 1인 차원 추가
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3) 
print(t12, t12.shape) # 2차원에 추가됨

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


#### * 텐서 펼치기

In [90]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
# 텐서를 1차원으로 평면화
t14 = t13.flatten()  # Shape becomes (6,)

# 결과 출력: 1차원 텐서
print(t14) 

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])

# 1차원으로 평면화
t16 = torch.flatten(t15)

# 두 번째 차원부터 평면화
t17 = torch.flatten(t15, start_dim=1)

# 결과 출력
print(t16) # 1차원 텐서
print(t17) # 2차원 텐서

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


#### * 차원 순서 변경 (Permute와 Transpose)

In [97]:
# 텐서 생성
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])

# 차원 순서 변경
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
# 텐서 생성
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
# 차원 순서 변경
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)

# 결과 출력: 각 차원의 크기는 변하지 않았지만, 순서는 변경 됨
print(t20) 
print(t21) 

# Transpose the tensor
# 텐서 전치
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

# 결과 출력: 각 차원의 크기는 변하지 않았지만, 순서는 변경 됨
print(t22)

# t메소드도 transpose 하는 역할을 함
t23 = torch.t(t19)  # Shape becomes (3, 2)

# 결과 출력: transpose 메소드에 의한 결과와 동일
print(t23)



torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat.py

In [1]:
import torch

#### * cat 으로 텐서 병합 (차원 유지)

In [3]:
# 여러개의 텐서 생성
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

# 여러 텐서를 연결하여 새로운 텐서 생성
t4 = torch.cat([t1, t2, t3], dim=1) # 두번째 차원을 따라 연결
print(t4.shape) # 두 번째

torch.Size([2, 6, 3])


In [2]:
# 1차원 텐서 2개 생성
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

# 첫번째 차원을 따라 텐서를 병합하여 새로운 텐서 생성
t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # 1차원에 모든 데이터 들어감 >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [4]:
# 2차원 텐서 2개 생성
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합 (두 번째 차원을 따라)
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

# 2차원 텐서간 병합 (첫 번째 차원을 따라)
t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [5]:
# 2차원 텐서 3개 생성
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

# 3개의 2차원 텐서 병합 (두 번째 차원을 따라 )
t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

# 3개의 2차원 텐서 병합 (첫 번째 차원을 따라 )
t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [6]:
# 3차원 텐서 생성
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

# 3차원 텐서 병합 (세 번째 차원을 따라)
t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

# 3차원 텐서 병합 (두 번째 차원을 따라)
t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

# 3차원 텐서 병합 (첫 번째 차원을 따라)
t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking.py

In [11]:
import torch

#### * stack을 이용한 병합 (차원 추가)

In [15]:
# 2개의 2차원 텐서 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# 1
# stack으로 텐서 병합 (세 번째 차원을 추가하며)
t3 = torch.stack([t1, t2], dim=0)

# cat으로 stack 효과 내기 (세 번째 차원 추가하고, 세 번째 차원을 따라 병합)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)

# 두 메소드로 병합된 텐서 출력 및 동등성 확인
print(t3.shape, t3.equal(t4)) # 일치함


# 2
# stack으로 텐서 병합 (두 번째 차원을 추가하며)
t5 = torch.stack([t1, t2], dim=1)

# cat으로 stack 효과 내기 (두 번째 차원 추가하고, 두 번째 차원을 따라 병합)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)

# 두 메소드로 병합된 텐서 출력 및 동등성 확인
print(t5.shape, t5.equal(t6)) # 일치함


# 3
# stack으로 텐서 병합 (첫 번째 차원을 추가하며)
t7 = torch.stack([t1, t2], dim=2)

# cat으로 stack 효과 내기 (첫 번째 차원 추가하고, 첫 번째 차원을 따라 병합)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)

# 두 메소드로 병합된 텐서 출력 및 동등성 확인
print(t7.shape, t7.equal(t8)) # 일치함

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [16]:
# 1차원 텐서 2개 생성
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])
print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

# 1
# stack으로 텐서 병합 (두 번째 차원을 추가하며)
t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

# cat으로 stack 효과 내기 (두 번째 차원 추가하고, 두 번째 차원을 따라 병합)
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True


#2
# stack으로 텐서 병합 (첫 번째 차원을 추가하며)
t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])

# cat으로 stack 효과 내기 (첫 번째 차원 추가하고, 첫 번째 차원을 따라 병합)
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


- 같은 사이즈의 텐서끼리만 쌓을 수 있다.

# n_tensor_vstack_hstack.py

In [20]:
import torch

#### * vstack을 이용하여 텐서 병합 (수직으로 스택)

In [22]:
# 1차원 텐서 생성
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])

# vstack으로 텐서 병합 (수직으로 스택)
t3 = torch.vstack((t1, t2)) # 튜플로 두 텐서 묶어서 전달하는 방식

# 출력 결과: 2차원 텐서, 두 번째 차원 2로 추가 됨
print(t3) 
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

# 2차원 텐서 생성
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])

# vstack으로 텐서 병합 (수직으로 스택)
t6 = torch.vstack((t4, t5))
# 출력 결과: 2차원 텐서, 두 번째 차원 크기 증가
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

# 3차원 텐서 생성
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

# vstack으로 텐서 병합 (수직으로 스택)
t9 = torch.vstack([t7, t8]) # 리스트로 두 텐서 묶어서 전달하는 방식

# 출력 결과 : 3차원 텐서, 세 번째 차원의 크기 증가
print(t9.shape)
# >>> (4, 2, 3)
print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


#### * hstack을 이용하여 텐서 병합 (수팽으로 스택)

In [23]:
# 1차원 텐서 생성
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])

# hstack으로 텐서 합병 (수평으로 스택)
t12 = torch.hstack((t10, t11))

# 출력 결과: 1차원 텐서, 첫 번째 차원 크기 증가
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])


# 2차원 텐서 생성
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])

# hstack으로 텐서 합병 (수평으로 스택)
t15 = torch.hstack((t13, t14))

# 출력 결과: 2차원 텐서, 첫 번째 차원 크기 증가
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

# 3차원 텐서 생성
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

# hstack으로 텐서 합병 (수평으로 스택)
t18 = torch.hstack([t16, t17])

# 출력 결과: 3차원 텐서, 두 번째 차원 크기 증가
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제 후기

 과제에서 복잡한 데이터를 효율적으로 관리할 수 있는 tenser의 기능을 자세히 알게되면서 텐서가 딥러닝 작업에 필수적이라는 것을 알게 되었다. 처음에는 NumPy 배열로 충분하지 않은가 의문을 갖기도 했지만, GPU를 사용이나 다양한 연산 등을 tenser에서 지원하기 때문에 그 필요성을 깨달을 수 있었다.

 
 그리고 tenser를 반환할 때 깊은 복사인지 얕은 복사인지 신경쓰는 것과 자주 shape나 size 같은 tenser의 정보를 확인해 보는 것이 텐서를 사용할 때 중요하다는 점도 배울 수 있었다. 데이터의 차원이 커질 수록 그 형태를 상상하기 어려워 지는데, tenser의 정보를 출력하여 확인하면 그 형태를 생각하고 관리하는데 큰 도움이 된다는 것도 느낄 수 있었다.